### PR TITLE
Add definition of d-separation

### PR DESCRIPTION
**Pull request by marcwjj**
To make it clearer the meaning of d-sep when there are multiple nodes in each group.

### CODE REVIEW

**Comment by kuleshov** [comment]
Thank you! Can you please write things so that there is less redundancy with the existing definition?

It's also okay if you don't have a formal "Definition" statement.

The Q, W variables in the existing text need to be re-named to X, Y.

**Comment by marcwjj** [comment]
Thanks for the feedback. I've condensed the paragraph and also updated to be consistently use Q,W,O notations.

**Comment by kuleshov** [comment]
Thank you, but my earlier comment was about not using Q, W (I don't know who added these), but instead to consistently use X, Y, Z everywhere.

Also, I see small grammar errors / typos in your edits. Please double-check these.

**Comment by marcwjj** [comment]
The Q, W, O notations are actually what Stefano uses in his lecture (slide 7 of lecture 3) , so I think it's helpful to keep a consistent references here. also the X,Y,Z notation right above are referring to nodes on active path, not the ones that we are testing d-separations about.

Rephrased the paragraph a bit more, please let me know if there's anything else to fix, thanks!

**Comment by kuleshov** [comment]
I know, but since there is no supporting material from the lecture that
uses Q, W, O, we should use X, Y, Z consistently.

I think this looks confusing to most onlien readers who are not looking at
Stefano's slides.

**Comment by jiamings** [comment]
I think this fix is written in the notes already by later commits.

**Pull request closed without merging**
